// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ToDoList_C_;

#nullable disable

namespace ToDoList_C_.Migrations.TaskListDB
{
    [DbContext(typeof(TaskListDBContext))]
    partial class TaskListDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("ToDoList_C_.TaskList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("DonePercentage")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("GotStar")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("lists");
                });

            modelBuilder.Entity("ToDoList_C_.ToDoTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TaskListId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TaskListId");

                    b.ToTable("ToDoTask");
                });

            modelBuilder.Entity("ToDoList_C_.ToDoTask", b =>
                {
                    b.HasOne("ToDoList_C_.TaskList", null)
                        .WithMany("taskList")
                        .HasForeignKey("TaskListId");
                });

            modelBuilder.Entity("ToDoList_C_.TaskList", b =>
                {
                    b.Navigation("taskList");
                });
#pragma warning restore 612, 618
        }
    }
}
