// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ToDoList_C_;

#nullable disable

namespace ToDoList_C_.Migrations
{
    [DbContext(typeof(UsersDBContext))]
    [Migration("20250515164253_AddMaxDaysInARow")]
    partial class AddMaxDaysInARow
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("ToDoList_C_.Star", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ListName")
                        .HasColumnType("TEXT");

                    b.Property<int>("Size")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("earnDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Star");
                });

            modelBuilder.Entity("ToDoList_C_.TaskList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DonePercentage")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("GotStar")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("dateTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TaskList");
                });

            modelBuilder.Entity("ToDoList_C_.ToDoTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TaskListId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TaskListId");

                    b.ToTable("ToDoTask");
                });

            modelBuilder.Entity("ToDoList_C_.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CurrentListId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxDaysInARow")
                        .HasColumnType("INTEGER");

                    b.Property<double>("averageTasksDone")
                        .HasColumnType("REAL");

                    b.Property<int>("daysInARow")
                        .HasColumnType("INTEGER");

                    b.Property<int>("starCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CurrentListId");

                    b.ToTable("users");
                });

            modelBuilder.Entity("ToDoList_C_.Star", b =>
                {
                    b.HasOne("ToDoList_C_.User", null)
                        .WithMany("stars")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("ToDoList_C_.ToDoTask", b =>
                {
                    b.HasOne("ToDoList_C_.TaskList", null)
                        .WithMany("taskList")
                        .HasForeignKey("TaskListId");
                });

            modelBuilder.Entity("ToDoList_C_.User", b =>
                {
                    b.HasOne("ToDoList_C_.TaskList", "CurrentList")
                        .WithMany()
                        .HasForeignKey("CurrentListId");

                    b.Navigation("CurrentList");
                });

            modelBuilder.Entity("ToDoList_C_.TaskList", b =>
                {
                    b.Navigation("taskList");
                });

            modelBuilder.Entity("ToDoList_C_.User", b =>
                {
                    b.Navigation("stars");
                });
#pragma warning restore 612, 618
        }
    }
}
